-- Unable to render TYPE DDL for object ESTODO.SYS_PLSQL_196741_112_1 with DBMS_METADATA attempting internal generator.
CREATE TYPE          SYS_PLSQL_196741_112_1 as object (YEAR NUMBER,
MONTH NUMBER,
DAY NUMBER,
DAYS_IN_MONTH NUMBER,
THE_DATE DATE);
