--------------------------------------------------------
--  Ref Constraints for Table TREATM_PARAM
--------------------------------------------------------

  ALTER TABLE "TREATM_PARAM" ADD CONSTRAINT "FK_DSRT_STATUS" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "TREATM_PARAM" ADD CONSTRAINT "FK_TRPA_DSRT_PARAM_TYPE" FOREIGN KEY ("PARAM_TYPE_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "TREATM_PARAM" ADD CONSTRAINT "FK_TRPA_DSRT_SUBJTYPE" FOREIGN KEY ("SUBJ_TYPE_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "TREATM_PARAM" ADD CONSTRAINT "FK_TRPA_DSRT_UNIT_TYPE" FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "TREATM_PARAM" ADD CONSTRAINT "FK_TRPA_DSRT_VALUE_TYPE" FOREIGN KEY ("VALUE_TYPE_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "TREATM_PARAM" ADD CONSTRAINT "FK_TRPA_SUB" FOREIGN KEY ("SUBJ_ID")
	  REFERENCES "SUBJECT" ("SUBJ_ID") ENABLE;
 
  ALTER TABLE "TREATM_PARAM" ADD CONSTRAINT "FK_TRPA_TRPM" FOREIGN KEY ("TREATM_ID")
	  REFERENCES "TREATM" ("TREATM_ID") ENABLE;
