REM INSERTING into WK_STAGE_ESDOMAIN_20160209
SET DEFINE OFF;
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values ('Saját készítésű adminisztrációs dokumentum',null,null,null,'Érkezett adminisztrációs dokumentum',null,null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Célja',null,null,null,'Célja',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'saját felhasználás',null,null,null,'dolgozó nevére érkezett');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'belső használatra',null,null,null,'belső használatra');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'belső használatra tulajdonosi körnek',null,null,null,'belső használatra tulajdonosi körnek');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'partnernek elküldendő',null,null,null,'partnernek visszaküldendő');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'hivatali beadásra',null,null,null,'hivatalnak visszaküldendő');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'tájékoztató (közvéleménynek)',null,null,null,'tájékoztató (közvéleménynek)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Forrás dokumentum',null,null,null,'Kapcsolódó dokumentum',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'nincs',null,null,null,'nincs');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'hivatkozás a dokumentum(ok)ra',null,null,null,'hivatkozás a dokumentum(ok)ra');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Cél dokumentum',null,null,null,'Cél dokumentum',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'nincs',null,null,null,'nincs');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'hivatkozás a dokumentum(ok)ra',null,null,null,'hivatkozás a dokumentum(ok)ra');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Belső véleményezés',null,null,null,'Belső véleményezés',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'tényközlő (nem kell véleményezni)',null,null,null,'tényközlő (nem kell véleményezni)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'belső véleményezésű',null,null,null,'belső véleményezésű');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'belső véleményezésű tulajdonosi hozzájárulással',null,null,null,'belső véleményezésű tulajdonosi hozzájárulással');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Belső véleményezés módja',null,null,null,'Belső véleményezés módja',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'dokumentum kitöltése kézzel',null,null,null,'dokumentum kitöltése kézzel');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'dokumentum kitöltése digitális szerkesztéssel',null,null,null,'dokumentum kitöltése digitális szerkesztéssel');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'véleményezés a dokumentumban kézzel',null,null,null,'véleményezés a dokumentumban kézzel');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'véleményezés a dokumentumban digitális szerkesztéssel',null,null,null,'véleményezés a dokumentumban digitális szerkesztéssel');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'véleményezés külön dokumentumban',null,null,null,'véleményezés külön dokumentumban');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'új verzió változáskövetéssel (eredeti dokumentum átdolgozása)',null,null,null,'új verzió változáskövetéssel (eredeti dokumentum átdolgozása)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'új verzió változáskövetés nélkül (eredeti dokumentum átdolgozása)',null,null,null,'új verzió változáskövetés nélkül (eredeti dokumentum átdolgozása)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Partneri véleményezés',null,null,null,'Partneri véleményezés',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'nem küldjük el a feldolgozás után',null,null,null,'nem küldjük vissza a feldolgozás után');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'tényközlő (elküldjük, de nem várunk vissza partneri véleményt)',null,null,null,'tényközlő (visszaküldjük, de nem várunk vissza partneri véleményt)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'elküldjük és a vélemény visszaérkezését várjuk',null,null,null,'elküldjük és a vélemény visszaérkezését várjuk');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Eredeti formátum',null,null,null,'Eredeti formátum',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'papíros (tárolási hely)',null,null,null,'papíros');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'digitális (szöveg, táblázat, kép, video)',null,null,null,'digitális (szöveg, táblázat, kép, video)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,null,null,null,null,'pdf nem szerkeszthető');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,null,null,null,null,'pdf szerkeszthető');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Feldolgozás végén Pdf formátum',null,null,null,'Feldolgozás végén Pdf formátum',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'nem készül pdf',null,null,null,'nem készül pdf');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'pdf létrehozása generálással (szerkeszthető/nem)',null,null,null,'pdf létrehozása generálással (szerkeszthető/nem)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'pdf létrehozása szkeneléssel (szerkeszthető/nem)',null,null,null,'pdf létrehozása szkeneléssel (szerkeszthető/nem)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Aláírás a feldolgozás végén',null,null,null,'Aláírás a feldolgozás végén',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'nem kell (elég a usernév digitális rögzítése)',null,null,null,'nem kell (elég a usernév digitális rögzítése)');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'kézi, cégszerű',null,null,null,'kézi, cégszerű');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'digitálisan hitelesített, cégszerű',null,null,null,'digitálisan hitelesített, cégszerű');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,'Projektzárás utáni archíválás',null,null,null,'Projektzárás utáni archíválás',null);
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'nem kell',null,null,null,'nem kell');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'kell 7 évig',null,null,null,'kell 7 évig');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'kell 25 évig',null,null,null,'kell 25 évig');
Insert into WK_STAGE_ESDOMAIN_20160209 (COLUMN1,COLUMN2,COLUMN3,COLUMN4,COLUMN5,COLUMN6,COLUMN7) values (null,null,'kell időkorlát nélkül',null,null,null,'kell időkorlát nélkül');
commit;
