--------------------------------------------------------
--  Constraints for Table DM_SUBJECT
--------------------------------------------------------

  ALTER TABLE "DM_SUBJECT" ADD CONSTRAINT "PK_DSUBJ" PRIMARY KEY ("DM_SUBJECT_ID") ENABLE;
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("MANDATORY" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("IS_GROUP" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("MULTIPLY" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("APPENDABLE" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("ROLL_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("SUBJ_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("ORDER_NO" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("SUBJ_PARAM_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("TABLE_ROLL" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("FROM_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("TO_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("CRD" NOT NULL DISABLE);
 
  ALTER TABLE "DM_SUBJECT" MODIFY ("CRU" NOT NULL DISABLE);
