--------------------------------------------------------
--  Constraints for Table DM_SUPER_TYP
--------------------------------------------------------

  ALTER TABLE "DM_SUPER_TYP" ADD CONSTRAINT "KEY_DSRT_SHORT_NAME" UNIQUE ("SUPER_TYPE_SHORT_NAME") ENABLE;
 
  ALTER TABLE "DM_SUPER_TYP" ADD CONSTRAINT "PK_DSRT" PRIMARY KEY ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("SUPER_TYP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("SUPER_TYPE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("FROM_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("TO_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("CRU" NOT NULL ENABLE);
 
  ALTER TABLE "DM_SUPER_TYP" MODIFY ("CRD" NOT NULL ENABLE);
